// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9wAdM4Qow3FrlUBurQq5QmhiEMF_imc',
    appId: '1:173295863423:web:d0afaf612e316f49f3e14a',
    messagingSenderId: '173295863423',
    projectId: 'flutterauthen-27269',
    authDomain: 'flutterauthen-27269.firebaseapp.com',
    storageBucket: 'flutterauthen-27269.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw9wHCeEGWW0eHQb3yAN1nHVV-3qZsXLw',
    appId: '1:173295863423:android:34c88187294f0b15f3e14a',
    messagingSenderId: '173295863423',
    projectId: 'flutterauthen-27269',
    storageBucket: 'flutterauthen-27269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAv-TX_28KYobY827FWbeH4DgnRQtPN4w',
    appId: '1:173295863423:ios:98b01050f9e0ea3ef3e14a',
    messagingSenderId: '173295863423',
    projectId: 'flutterauthen-27269',
    storageBucket: 'flutterauthen-27269.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAv-TX_28KYobY827FWbeH4DgnRQtPN4w',
    appId: '1:173295863423:ios:7fc8f44fccd949b8f3e14a',
    messagingSenderId: '173295863423',
    projectId: 'flutterauthen-27269',
    storageBucket: 'flutterauthen-27269.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
